name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    environment: BUILD

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}
        docker build . --file Dockerfile --tag jenciso/registry-proxy:$IMAGE_TAG

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Push image
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}
        echo "Pushing image: jenciso/registry-proxy:$IMAGE_TAG"
        docker tag jenciso/registry-proxy:$IMAGE_TAG jenciso/registry-proxy:latest
        docker push jenciso/registry-proxy:$IMAGE_TAG
        docker push jenciso/registry-proxy:latest